base_config: configs/DTD/base.yaml
proj: DTD
name: DTD-SD1.5

data: 
  base_dataset: DTD
  base_root: /grp01/cs_hszhao/cs002u03/dataset/dtd/dtd_split
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SD1_5/DTD
  num_extra: "all"
  # num_extra: 10000
  filter: False


# model: resnet50_pretrained