base_config: configs/IN200_S/base.yaml
proj: IN-200-sub
name: IN-200-sub-gridmask

data: 
  base_dataset: IN200_sub
  base_root: /grp01/cs_hszhao/cs002u03/dataset/IN200_S
  augmentation: gridmask # cutout  gridmask  randaug

  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/dataset/IN200_S/train
  num_extra: "extra"
  filter: False
  multiples: 5
  
# hps:
#   lr: 0.1

# model: resnet50_pretrained