base_config: configs/IN200_S/base.yaml
proj: IN-200-sub
name: IN-200-sub-GIF

data: 
  base_dataset: IN200_sub
  base_root: /grp01/cs_hszhao/cs002u03/dataset/IN200_S
  extra_dataset: BasicDataset
  # extra_root: /grp01/cs_hszhao/cs002u03/GIF/IN200-sub_expansion
  extra_root: /grp01/cs_hszhao/cs002u03/GIF/IN200-sub_expansion_5x
  num_extra: "all"
  filter: False
  # multiple: 1