base_config: configs/IN200_S/base.yaml
proj: IN-200-sub
name: IN-200-sub-NoAlign

data: 
  base_dataset: IN200_sub
  base_root: /grp01/cs_hszhao/cs002u03/dataset/IN200_S
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SEI/IN200S-NoAlign-2.0
  num_extra: "all"
  # num_extra: "extra"
  filter: False
  # multiples: 5

filter:
  load: False

# hps:
#   lr: 0.1