base_config: configs/IN200_S/base.yaml
proj: IN-200-sub
name: IN-200-sub-SD1.5

data: 
  base_dataset: IN200_sub
  base_root: /grp01/cs_hszhao/cs002u03/dataset/IN200_S
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SD1_5/IN200S
  num_extra: "all"
  # num_extra: 10000
  filter: False

# hps:
#   lr: 0.1