base_config: configs/IN100_sub/base.yaml
proj: IN-100-sub
name: IN-100-sub-gridmask

data: 
  base_dataset: IN100_sub
  base_root: /grp01/cs_hszhao/cs002u03/dataset/IN100_sub
  augmentation: gridmask # cutout  gridmask  randaug

  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/dataset/IN100_sub/train
  num_extra: "extra"
  filter: False
  multiples: 5