base_config: configs/IN100_sub/base.yaml
proj: IN-100-sub
name: IN-100-sub-base

data: 
  base_dataset: IN100_sub
  base_root: /grp01/cs_hszhao/cs002u03/dataset/IN100_sub
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SD1_5/IN100S-5x
  num_extra: "all"
  # num_extra: 10000
  filter: False
