base_config: configs/Flowers102/base.yaml
proj: Flowers102
name: Flowers-Ablation-Gaussian-5x

data: 
  base_dataset: Flowers102
  base_root: /grp01/cs_hszhao/cs002u03/dataset/Flower102
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SEI/Flowers-Gaussian-2.0
  num_extra: "all"
  # num_extra: "extra"
  filter: True
  multiples: 5

# hps:
#   lr: 0.1

# model: resnet50_pretrained