base_config: configs/Flowers102/base.yaml
proj: Flowers102
name: Flowers-randaug-5x

data: 
  base_dataset: Flowers102
  base_root: /grp01/cs_hszhao/cs002u03/dataset/Flower102
  augmentation: randaug # cutout  gridmask  randaug

  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/dataset/Flower102/train
  num_extra: "extra"
  filter: False
  multiples: 5
  
# hps:
#   lr: 0.1

# model: resnet50_pretrained