base_config: configs/Cub2011/base.yaml
proj: CUB
name: CUB-DALLE

data: 
  base_dataset: Cub2011
  base_root: /grp01/cs_hszhao/cs002u03/dataset/CUB_200_2011
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/DALLE2/CUB
  num_extra: "all"
  # num_extra: "extra"
  filter: False
  multiples: 5

# hps:
#   lr: 0.1

# model: resnet50_pretrained