base_config: configs/Cub2011/base.yaml
proj: CUB
name: CUB-Gaussian-2.0-ration-1.5

data: 
  base_dataset: Cub2011
  base_root: /grp01/cs_hszhao/cs002u03/dataset/CUB_200_2011
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SEI/CUB-Gaussian-2.0
  # num_extra: "all"
  num_extra: "extra"
  filter: True
  multiples: 5

filter_ratio: 0.667
data_pt: /grp01/cs_hszhao/cs002u03/output/SEI_filter/embeddings/Cub2011/CUB-Gaussian-2.0-filtered/aug_data.pt
# 1:1.5  0.667
# 1:2    0.5
# 1:3    0.333
# 1:4    0.25

# model: resnet50_pretrained