base_config: configs/Cars196/base.yaml
proj: Cars196
name: Cars-SD

data: 
  base_dataset: Cars196
  base_root: /grp01/cs_hszhao/cs002u03/dataset/StanfordCars/cars
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SD1_5/Cars
  num_extra: "all"
  # num_extra: 10000
  filter: False

# hps:
#   lr: 0.1

# model: resnet50_pretrained