base_config: configs/PETs/base.yaml
proj: PETs
name: PETs-GIF

data: 
  base_dataset: PETs
  base_root: /grp01/cs_hszhao/cs002u03/dataset/PETs
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/GIF/PETs_expansion
  # num_extra: "all"
  num_extra: "extra"
  multiples: 10
  filter: False
  

# hps:
#   lr: 0.1

# model: resnet50_pretrained