base_config: configs/PETs/base.yaml
proj: PETs
name: PETs-Gaussian-2.0-ration-1.5

data: 
  base_dataset: PETs
  base_root: /grp01/cs_hszhao/cs002u03/dataset/PETs
  extra_dataset: BasicDataset
  extra_root: /grp01/cs_hszhao/cs002u03/output/SEI/PETs-Gaussian-2.0
  # num_extra: "all"
  num_extra: "extra"
  filter: True
  multiples: 5

filter_ratio: 0.667
data_pt: /grp01/cs_hszhao/cs002u03/output/SEI_filter/embeddings/PETs/PETs-Gaussian-filtered-2.0/aug_data.pt
# 1:1.5  0.667
# 1:2    0.5
# 1:3    0.333
# 1:4    0.25

# model: resnet50_pretrained